/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiDashboardDashboardGet$Params } from './fn/dashboard/api-dashboard-dashboard-get';
export { apiDashboardDashboardGet } from './fn/dashboard/api-dashboard-dashboard-get';
export type { ApiIncidentsListaIncidentsGet$Params } from './fn/incidents/api-incidents-lista-incidents-get';
export { apiIncidentsListaIncidentsGet } from './fn/incidents/api-incidents-lista-incidents-get';
export type { ApiIncidentsIncidentByIdIdIncidntGet$Params } from './fn/incidents/api-incidents-incident-by-id-id-incidnt-get';
export { apiIncidentsIncidentByIdIdIncidntGet } from './fn/incidents/api-incidents-incident-by-id-id-incidnt-get';
export type { ApiIncidentsPost$Params } from './fn/incidents/api-incidents-post';
export { apiIncidentsPost } from './fn/incidents/api-incidents-post';
export type { ApiIncidentsUpdateObservationPatch$Params } from './fn/incidents/api-incidents-update-observation-patch';
export { apiIncidentsUpdateObservationPatch } from './fn/incidents/api-incidents-update-observation-patch';
export type { ApiShovelsListadepalasGet$Params } from './fn/shovels/api-shovels-listadepalas-get';
export { apiShovelsListadepalasGet } from './fn/shovels/api-shovels-listadepalas-get';
export type { ApiShovelsIdShovelGet$Params } from './fn/shovels/api-shovels-id-shovel-get';
export { apiShovelsIdShovelGet } from './fn/shovels/api-shovels-id-shovel-get';
export type { ApiShovelsPost$Params } from './fn/shovels/api-shovels-post';
export { apiShovelsPost } from './fn/shovels/api-shovels-post';
export type { ApiShovelsActulziarStatusPatch$Params } from './fn/shovels/api-shovels-actulziar-status-patch';
export { apiShovelsActulziarStatusPatch } from './fn/shovels/api-shovels-actulziar-status-patch';
export type { GetWeatherForecast$Plain$Params } from './fn/weather-forecast/get-weather-forecast-plain';
export { getWeatherForecast$Plain } from './fn/weather-forecast/get-weather-forecast-plain';
export type { GetWeatherForecast$Json$Params } from './fn/weather-forecast/get-weather-forecast-json';
export { getWeatherForecast$Json } from './fn/weather-forecast/get-weather-forecast-json';
