/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { IncidentInsertDto } from './models/incident-insert-dto';
export type { IncidentUpdateDto } from './models/incident-update-dto';
export type { ShovelInsertDto } from './models/shovel-insert-dto';
export type { ShovelUpdateDto } from './models/shovel-update-dto';
export type { WeatherForecast } from './models/weather-forecast';
