/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IncidentInsertDto {
  datetimepic?: string | null;
  idShovel?: number | null;
  idStatusIncident?: number | null;
  idUser?: number | null;
  path?: string | null;
  rawname?: string | null;
}
