/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IncidentUpdateDto {
  idINCIDNT?: number | null;
  idStatusIncident?: number | null;
  observation?: string | null;
}
